[[constraint]]
	name = "github.com/thehowl/fasthttprouter"
	version = "0.2.1"

[[constraint]]
	name = "github.com/erikdubbelboer/fasthttp"
	branch = "master"

[[constraint]]
	name = "github.com/jinzhu/gorm"
	version = "v1.9.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.10.2"

[[constraint]]
  branch = "master"
  name = "zxq.co/x/ripple"
